[OPENAI_API_KEY]
OPENAI_API_KEY = "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"  # Replace with your real API key
