[OPENAI_API_KEY]
OPENAI_API_KEY = "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"
